In [1]:
import numpy as np
list1=[1,2,3]
np.array(list1)

array([1, 2, 3])

In [2]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,10) # 0 included 10 excluded

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2) # 0 included 11 excluded and at interval of 2

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.linspace(0,5,10)  # starting from 0 to 5 we get 10 evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.max()

24

In [17]:
arr.min()

0

In [18]:
arr.argmax()

24

In [20]:
arr.argmin()

0

In [22]:
arr.shape

(25,)