In [23]:
import numpy as np

In [24]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr_copy=arr.copy()  # to store copy of an array
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
sl=arr[0:6] 
sl[:]=100
arr  # changes made in 'sl' are reflected in arr to avoid that you can use 'copy'

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [33]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2D array

In [34]:
arr2=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr2[0][1] 

10

In [36]:
arr2[0,1]

10

In [37]:
arr2[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr 

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [41]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr= arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr<3]

array([0, 1, 2])

In [48]:
arr2=np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])